language: php
php:
  - 5.3
  - 5.4
  - 7.1

sudo: false

branches:
  only:
    - master

install: composer install

script: phpunit

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240
  mail: p.scheit@ps-webforge.com