language: php
php:
  - 7.1

sudo: false

branches:
  only:
    - master

before_install:
  - composer require --dev --no-update phpunit/phpunit ~5.7

install: composer install

script: phpunit

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240
  mail: p.scheit@ps-webforge.com