language: php
php:
  - 5.6
  - 7.1

sudo: false

branches:
  only:
    - master

before_install:
  - composer require --dev --no-update phpunit/phpunit ~5.7

install: composer install

script: vendor/bin/phpunit

notifications:
  mail: p.scheit@ps-webforge.com